---
- import_tasks: ssh.yml
  tags: [security, ssh]

- import_tasks: firewall.yml
  tags: [security, firewall]

- import_tasks: sysctl.yml
  tags: [security, sysctl]

- import_tasks: packages.yml
  tags: [security, packages]

- import_tasks: auditd.yml
  tags: [security, audit]
